docs_dir: docs/book
site_dir: docs/html
extra:
  project: Frontend
  current_version: v5
  versions:
    - v5
nav:
  - Home: index.md
  - v5:
      - Introduction: v5/introduction/introduction.md
      - Overview:
          - "Server Requirements": v5/introduction/server-requirements.md
          - "File Structure": v5/introduction/file-structure.md
          - "Packages": v5/introduction/packages.md
      - Installation:
          - "Introduction": v5/installation/installation-intro.md
          - "Getting Started": v5/installation/getting-started.md
          - "Composer": v5/installation/composer.md
          - "Configuration Files": v5/installation/configuration-files.md
          - "Doctrine ORM": v5/installation/doctrine-orm.md
          - "Development Mode": v5/installation/development-mode.md
          - "Running the Application": v5/installation/running-application.md
          - "FAQ": v5/installation/faq.md
      - How to:
          - "Create Database Migrations": v5/how-to/creating-migrations.md
          - "Create Database Fixtures": v5/how-to/creating-fixtures.md
          - "Configure Authorizations": v5/how-to/authorization.md
          - "Use NPM Commands": v5/how-to/npm_commands.md
          - "Inject Dependencies": v5/how-to/dependency-injection.md
          - "Set Up CSRF": v5/how-to/csrf.md
          - "Anonymize Accounts": v5/how-to/account-anonymization.md
site_name: frontend
site_description: "Dotkernel Frontend"
repo_url: "https://github.com/dotkernel/frontend"
plugins:
  - search
